export class WP2StaticAdminPageModel {

  allowOfflineUsage: HTMLElement;
  baseUrl: HTMLElement;
  baseUrlZip: HTMLElement;
  cancelExportButton: HTMLElement;
  createZip: HTMLElement;
  currentAction: HTMLElement;
  deleteCrawlCache: HTMLInputElement;
  detectEverythingButton: HTMLInputElement;
  detectNothingButton: HTMLInputElement;
  detectionOptionsInputs: <Array>HTMLInputElement;
  downloadExportLogButton: HTMLInputElement;
  downloadZIP: HTMLElement;
  exportDuration: HTMLElement;
  formProcessorDescription: HTMLElement;
  formProcessorEndpoint: HTMLElement;
  formProcessorSelect: HTMLElement;
  formProcessorWebsite: HTMLElement;
  generalOptions: HTMLElement;
  goToAdvancedTabButton: HTMLElement;
  goToDeployTabButton: HTMLElement;
  goToDeployTabLink: HTMLElement;
  goToDetectionTabButton: HTMLElement;
  goToMyStaticSite: HTMLElement;
  hiddenAJAXAction: HTMLInputElement;
  hiddenActionField: HTMLInputElement;
  initialCrawlListCount: HTMLElement;
  initialCrawlListLoader: HTMLElement;
  navigationTabs: <Array>HTMLElement;
  previewInitialCrawlListButton: HTMLElement;
  progress: HTMLElement;
  pulsateCSS: HTMLElement;
  resetDefaultSettingsButton: HTMLElement;
  saveSettingsButton: HTMLElement;
  saveAndReloadButton: HTMLElement;
  selectedDeploymentMethod: HTMLElement;
  sendSupportRequestButton: HTMLElement;
  sendSupportRequestContent: HTMLElement;
  sendSupportRequestIncludeLog: HTMLElement;
  settingsBlocks: <Array>HTMLElement;
  startExportButton: HTMLElement;
  supportRequestEmail: HTMLElement;
  targetFolder: HTMLElement;
  vendorNotices: <Array>HTMLElement;

  constructor() {
    this.allowOfflineUsage = document.getElementById('allowOfflineUsage');
    this.baseUrl = document.getElementById('baseUrl');
    this.baseUrlZip = document.getElementById('baseUrl-zip');
    this.cancelExportButton = document.getElementByClass('cancelExportButton');
    this.createZip = document.getElementById('createZip');
    this.currentAction = document.getElementById('current_action');
    this.deleteCrawlCache = document.getElementById('deleteCrawlCache');
    this.detectEverythingButton = document.getElementById('detectEverythingButton');
    this.detectNothingButton = document.getElementById('detectNothingButton');
    this.detectionOptionsInputs = document.querySelectorAll('#detectionOptionsTable input[type="checkbox"]');
    this.downloadExportLogButton = document.getElementById('downloadExportLogButton');
    this.downloadZIP = document.getElementById('downloadZIP');
    this.exportDuration = document.getElementById('exportDuration');
    this.formProcessorDescription = document.getElementById('form_processor_description');
    this.formProcessorEndpoint = document.getElementById('form_processor_endpoint');
    this.formProcessorSelect = document.getElementById('form_processor_select');
    this.formProcessorWebsite = document.getElementById('form_processor_website');
    this.generalOptions = document.getElementById('general-options');
    this.goToAdvancedTabButton = document.getElementById('GoToAdvancedTabButton');
    this.goToDeployTabButton = document.getElementById('GoToDeployTabButton');
    this.goToDeployTabLink = document.getElementById('GoToDeployTabLink');
    this.goToDetectionTabButton = document.getElementById('GoToDetectionTabButton');
    this.goToMyStaticSite = document.getElementById('goToMyStaticSite');
    this.hiddenAJAXAction = document.getElementById('hiddenAJAXAction');
    this.hiddenActionField = document.getElementByClass('hiddenActionField');
    this.initialCrawlListCount = document.getElementById('initial_crawl_list_count');
    this.initialCrawlListLoader = document.getElementById('initial_crawl_list_loader');
    this.navigationTabs = document.querySelectorAll(".nav-tab");
    this.previewInitialCrawlListButton = document.getElementById('preview_initial_crawl_list_button');
    this.progress = document.getElementById('progress');
    this.pulsateCSS = document.getElementByClass('pulsate-css');
    this.resetDefaultSettingsButton = document.getElementByClass('resetDefaultSettingsButton');
    this.saveSettingsButton = document.getElementByClass('saveSettingsButton');
    this.saveAndReloadButton = document.getElementByClass('save-and-reload');
    this.selectedDeploymentMethod = document.getElementByClass('selected_deployment_method');
    this.sendSupportRequestButton = document.getElementById('send_supportRequest');
    this.sendSupportRequestContent = document.getElementById('supportRequestContent');
    this.sendSupportRequestEmail = document.getElementById('supportRequestEmail');
    this.sendSupportRequestIncludeLog = document.getElementById('supportRequestIncludeLog');
    this.settingsBlocks = document.querySelectorAll('[class$="_settings_block"]');
    this.startExportButton = document.getElementById('startExportButton');
    this.targetFolder = document.getElementById('targetFolder');
    this.vendorNotices = document.querySelectorAll(".update-nag, .updated, .error, .is-dismissible, .elementor-message");

  } 
}

