export class WP2StaticOptions {

  public additionalUrls: string
  public allowOfflineUsage: boolean
  public baseHREF: string
  public baseUrlfolder: string
  public baseUrlzip: string
  public basicAuthPassword: string
  public basicAuthUser: string
  public completionEmail: string
  public crawlPort: number
  public crawlUserAgent: string
  public crawlDelay: number
  public createEmptyFavicon: boolean
  public currentDeploymentMethod: string
  public currentDeploymentMethodProduction: string
  public delayBetweenAPICalls: number
  public deployBatchSize: number
  public detectArchives: boolean
  public detectAttachments: boolean
  public detectCategoryPagination: boolean
  public detectChildTheme: boolean
  public detectCommentPagination: boolean
  public detectComments: boolean
  public detectCustomPostTypes: boolean
  public detectFeedURLs: boolean
  public detectHomepage: boolean
  public detectPages: boolean
  public detectParentTheme: boolean
  public detectPluginAssets: boolean
  public detectPostPagination: boolean
  public detectPosts: boolean
  public detectUploads: boolean
  public detectVendorCacheDirs: boolean
  public detectWPIncludesAssets: boolean
  public displayDashboardWidget: boolean
  public dontUseCrawlCaching: boolean
  public excludeURLs: string
  public forceHTTPS: boolean
  public forceRewriteSiteURLs: boolean
  public includeDiscoveredAssets: boolean
  public parseCSS: boolean
  public redeployOnPostUpdates: boolean
  public removeCanonical: boolean
  public removeConditionalHeadComments: boolean
  public removeHTMLComments: boolean
  public removeWPLinks: boolean
  public removeWPMeta: boolean
  public renameRules: string
  public rewriteRules: string
  public targetFolder: string
  public useActiveFTP: boolean
  public useBaseHref: string
  public useBasicAuth: boolean
  public useDocumentRelativeURLs: boolean
  public useSiteRootRelativeURLs: boolean

  constructor(optionsFromDB: string) {
    const parsedOptions = JSON.parse(optionsFromDB)

    this.additionalUrls = parsedOptions.additionalUrls
    this.allowOfflineUsage = parsedOptions.allowOfflineUsage
    this.baseHREF = parsedOptions.baseHREF
    this.baseUrlfolder = parsedOptions.baseUrlfolder
    this.baseUrlzip = parsedOptions.baseUrlzip
    this.basicAuthPassword = parsedOptions.basicAuthPassword
    this.basicAuthUser = parsedOptions.basicAuthUser
    this.completionEmail = parsedOptions.completionEmail
    this.crawlDelay = parsedOptions.crawlDelay
    this.crawlPort = parsedOptions.crawlPort
    this.crawlUserAgent = parsedOptions.crawlUserAgent
    this.createEmptyFavicon = parsedOptions.createEmptyFavicon
    this.currentDeploymentMethod = parsedOptions.currentDeploymentMethod
    this.currentDeploymentMethodProduction = parsedOptions.currentDeploymentMethodProduction
    this.delayBetweenAPICalls = parsedOptions.delayBetweenAPICalls
    this.detectArchives = parsedOptions.detectArchives
    this.detectAttachments = parsedOptions.detectAttachments
    this.detectCategoryPagination = parsedOptions.detectCategoryPagination
    this.detectChildTheme = parsedOptions.detectChildTheme
    this.detectCommentPagination = parsedOptions.detectCommentPagination
    this.detectComments = parsedOptions.detectComments
    this.detectCustomPostTypes = parsedOptions.detectCustomPostTypes
    this.detectFeedURLs = parsedOptions.detectFeedURLs
    this.detectHomepage = parsedOptions.detectHomepage
    this.detectPages = parsedOptions.detectPages
    this.detectParentTheme = parsedOptions.detectParentTheme
    this.detectPluginAssets = parsedOptions.detectPluginAssets
    this.detectPostPagination = parsedOptions.detectPostPagination
    this.detectPosts = parsedOptions.detectPosts
    this.detectUploads = parsedOptions.detectUploads
    this.detectVendorCacheDirs = parsedOptions.detectVendorCacheDirs
    this.detectWPIncludesAssets = parsedOptions.detectWPIncludesAssets
    this.deployBatchSize = parsedOptions.deployBatchSize
    this.displayDashboardWidget = parsedOptions.displayDashboardWidget
    this.dontUseCrawlCaching = parsedOptions.dontUseCrawlCaching
    this.includeDiscoveredAssets = parsedOptions.includeDiscoveredAssets
    this.excludeURLs = parsedOptions.excludeURLs
    this.forceHTTPS = parsedOptions.forceHTTPS
    this.forceRewriteSiteURLs = parsedOptions.forceRewriteSiteURLs
    this.parseCSS = parsedOptions.parsedOptions
    this.redeployOnPostUpdates = parsedOptions.redeployOnPostUpdates
    this.removeConditionalHeadComments = parsedOptions.removeConditionalHeadComments
    this.removeHTMLComments = parsedOptions.removeHTMLComments
    this.removeCanonical = parsedOptions.removeCanonical
    this.removeWPLinks = parsedOptions.removeWPLinks
    this.removeWPMeta = parsedOptions.removeWPMeta
    this.rewriteRules = parsedOptions.rewriteRules
    this.renameRules = parsedOptions.renameRules
    this.targetFolder = parsedOptions.targetFolder
    this.useActiveFTP = parsedOptions.useActiveFTP
    this.useBaseHref = parsedOptions.useBaseHref
    this.useBasicAuth = parsedOptions.useBasicAuth
    this.useDocumentRelativeURLs = parsedOptions.useDocumentRelativeURLs
    this.useSiteRootRelativeURLs = parsedOptions.useSiteRootRelativeURLs
  }
}

