<div class="bunnycdn_settings_block" style="display:none;">

  <div class="notice notice-error inline">
    <h2 class="title">Premium deployment option</h2>

    <p>Get all the deployment options and advanced features with a 
      <a href="https://wp2static.com" target="_blank">premium subscription</a>.</p>

    <p>Exporting to this method will not work without upgrading, but you can stil deploy to BunnyCDN using the ZIP option and manually uploading to S3.</p>

  </div>

  <br>

  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-bunnycdn"><?php echo __('Base URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-bunnycdn', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnPullZoneName"><?php echo __('Pull Zone', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnPullZoneName', 'Pull Zone', 'ie, mybunnypullzone, etc . This will do a cache purge once all files are transferred '); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnAPIKey"><?php echo __('API Key', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnAPIKey', 'API Key', '', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnRemotePath"><?php echo __('Subdirectory', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnRemotePath', 'BunnyCDN Remote Path', 'will attempt to create folder recursively if non-existent'); ?>
        </td>
      </tr>
    </tbody>
  </table>
</div>
