<div class="bunnycdn_settings_block" style="display:none;">
  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-bunnycdn"><?php echo __('Destination URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-bunnycdn', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnStorageZoneName"><?php echo __('Storage Zone', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnStorageZoneName', 'Storage Zone Name', 'ie, mybunnystoragezone. This is where the files will be uploaded to. '); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnStorageZoneAccessKey"><?php echo __('Storage Zone Access Key', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnStorageZoneAccessKey', 'Storage Zone Access Key', 'Find in your Storage Zone settings', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnPullZoneID"><?php echo __('Pull Zone ID', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnPullZoneID', 'Pull Zone ID', 'Numeric. ie, 1234. This will do a cache purge once all files are transferred', 'number'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnPullZoneAccessKey"><?php echo __('Pull Zone Access Key', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnPullZoneAccessKey', 'Pull Zone Access Key', 'Find in your Account settings', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunnycdnRemotePath"><?php echo __('Subdirectory', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'bunnycdnRemotePath', 'BunnyCDN Remote Path', 'will attempt to create folder recursively if non-existent'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="bunny_test"><?php echo __('Test BunnyCDN Settings', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <button id="bunny-test-button" type="button" class="btn-primary button">Test BunnyCDN Settings</button>

    <p>Note: In order to create files in bulk via BunnyCDN's API, the plugin will first make a commit which deletes all files in the repository. Being git, this is easily reversible, but bears a mention, in case you are suprised. BunnyCDN will soon support force creating files which already exist, at which point, we will be able to upload just the files you want, without removing any existing ones.</p>



        </td>
      </tr>
    </tbody>
  </table>
</div>
