
<div class="folder_settings_block" style="display:none;">

	<img style="width:40px;float:left;margin-right:10px;" src="<?php echo plugins_url( 'images/folder_icon.png', dirname(__FILE__)) ?>" />

<ul>
	<li>
		<b>Testing the plugin quickly</b> by exporting to a subfolder of your current domain, you can check how it will look when published and make any adjustments needed. After the export, you should be able to see how your site looks in static html at: <a id="folderPreviewURL" href="<?php echo get_site_url() . '/mystatictest'; ?>/" target="_blank"><?php echo get_site_url() . '/mystatictest'; ?>/</a>
	</li>

	<br style="clear:both;" />

					<p>

					  <input style="display:none;" type="url" id="baseUrl-folder" name="baseUrl-folder" size="50" value="<?php echo get_site_url() . '/mystaticsite'; ?>/" />

<br>
<br>

					  <strong><label for="targetFolder"><?php echo __('Target folder to deploy to', 'static-html-output-plugin');?></label></strong>
					  <p>
						<i><?php echo __("You don't need to set this in all cases, but if you do, it will deploy your static site to a subdirectory on this same server you are running WordPress on.", 'static-html-output-plugin');?></i>
					  </p> 
					  <input type="url" id="targetFolder" name="targetFolder" size="50" value="mystaticsite" />
					</p>


</div>
