
<div class="folder_settings_block">

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
          <label for="targetFolder"><?php echo __('Target folder to deploy to', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <input id="targetFolder" name="targetFolder" class="regular-text" 
          value="<?php echo $this->options->targetFolder ? $this->options->targetFolder : 'mystaticsite'; ?>" /><br>

        <p>By exporting to a subfolder on your current server, you can check how it will look when published and make any adjustments needed. After the export, you should be able to see how your site looks in static html at: <a id="folderPreviewURL" href="<?php echo get_site_url() . '/mystatictest'; ?>/" target="_blank"><?php echo get_site_url() . '/mystatictest'; ?>/</a></p>
      </td>
    </tr>
  </tbody>
</table>


<input style="display:none;" type="url" id="baseUrl-folder" name="baseUrl-folder" />


</div>
