
<div class="folder_settings_block" style="display:none;">

	<img style="width:40px;float:left;margin-right:10px;" src="<?php echo plugins_url( 'images/folder_icon.png', dirname(__FILE__)) ?>" />

Generate a static copy of your site to a directory on this server, from where you can copy it somewhere else or symlink to use in production, for example.

<!--
	<p>Generating a static copy of the website on your server can be useful in a variety of scenarios. The below example use cases will give you an idea of what to set your Base Url option to.</p>

<ul>
	<li>
		<b>Testing the plugin quickly</b> by exporting to a subfolder of your current domain, you can check how it will look when published and make any adjustments needed. In this case, you should set the <b>Base Url</b> to <?php echo get_site_url() . '/mystatictest'; ?> and the <b>Target directory to deploy to</b> to <?php echo ABSPATH; ?>mystatictest.
	</li>

	<li>
		<b>Running WordPress from a subfolder and publishing your site on the domain's root</b>
	</li>	

-->

	<br style="clear:both;" />

	<br>

					  <strong><label><?php echo __('Settings for the folder deployment method', 'static-html-output-plugin');?></label></strong>

					<p>


					  <strong><label for="baseUrl"><?php echo __('Base Url', 'static-html-output-plugin');?></label></strong>
					  <p>
						<i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i>
					  </p> 

					  <input type="url" id="baseUrl-folder" name="baseUrl-folder" size="50" placeholder="http://mystaticsite.com" />
					</p>


</div>
