<div class="ftp_settings_block" style="display:none;">

  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
					  <label for="baseUrl"><?php echo __('Base URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-ftp', 'http://mystaticsite.com', '', ''); ?><br>

					  <p> <i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i> </p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpServer"><?php echo __('FTP Server', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpServer', '198.176.1.23', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpPort"><?php echo __('FTP Port', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpPort', '21', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ftpUsername"><?php echo __('FTP Username', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpUsername', 'FTP Username', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpPassword"><?php echo __('FTP Password', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpPassword', 'FTP Password', '', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpRemotePath"><?php echo __('FTP Remote Path', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpRemotePath', 'FTP Remote Path', 'will attempt to create folder recursively if non-existent'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpTLS"><?php echo __('Use FTPS (TLS)', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayCheckbox($this, 'ftpTLS', 'Use FTP with TLS'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="useActiveFTP"><?php echo __('Use active FTP', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayCheckbox($this, 'useActiveFTP', 'Use active FTP (defaults to passive mode) <a href="https://stackoverflow.com/q/1699145/1668057" target="_blank">What\'s the difference?</a>'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ftp_test"><?php echo __('Test FTP Credentials', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <button id="ftp-test-button" type="button" class="btn-primary button">Test FTP Settings</button>
          <div class="spinner is-active" style="float:none;width:auto;height:auto;padding:10px 0 10px 50px;;"> </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>
