<div class="ftp_settings_block" style="display:none;">

  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
					  <label for="baseUrl"><?php echo __('Base URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-ftp', 'http://mystaticsite.com', '', ''); ?><br>

					  <p> <i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i> </p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpServer"><?php echo __('FTP Server', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpServer', '198.176.1.23', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ftpUsername"><?php echo __('FTP Username', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpUsername', 'FTP Username', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpPassword"><?php echo __('FTP Password', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpPassword', 'FTP Password', '', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="ftpRemotePath"><?php echo __('FTP Remote Path', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ftpRemotePath', 'FTP Remote Path', 'will attempt to create folder recursively if non-existent'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
					  <label for="useActiveFTP"><?php echo __('Use active FTP', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayCheckbox($this, 'useActiveFTP', 'Use active FTP (defaults to passive mode) <a href="https://stackoverflow.com/q/1699145/1668057" target="_blank">What\'s the difference?</a>'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ftpBlobIncrement"><?php echo __('Transfer Batch Size', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <select name="ftpBlobIncrement" id="ftpBlobIncrement">
<?php 
  // TODO: shift this into helper function for select
  $increments = array(1, 5, 10, 25, 50, 100, 500, 1000, 999999);

  foreach($increments as $increment) :
       if ($increment == 999999): ?>
            <option value="999999"<?php echo $this->options->ftpBlobIncrement == $increment ? ' selected' : ''; ?>>Maximum</option>
<?php else: ?>
            <option value="<?php echo $increment; ?>"<?php echo $this->options->ftpBlobIncrement == $increment ? ' selected' : ''; ?>><?php echo $increment; ?></option>

<?php endif; 
         endforeach; ?>
          </select><br>

          <p>This is set to 1, by default, in order to avoid execution limit timeouts on restricted environments, such as shared hosting servers. Each increment is the amount of files the server will try to upload to FTP on each request. Incrementing this will speed up your exports, by processing more are a time. If your export is failing, due to execution limits r FTP API rate limits being reached, try setting this to a lower number.</p>

        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ftpBlobDelay"><?php echo __('Delay Between Batches', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <select name="ftpBlobDelay" id="ftpBlobDelay">
<?php 
  // TODO: shift this into helper function for select
  $increments = array(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 3, 4, 10);

  foreach($increments as $increment) : ?>
            <option value="<?php echo $increment; ?>"<?php echo $this->options->ftpBlobDelay == $increment ? ' selected' : ''; ?>><?php echo $increment; ?></option>
 <?php endforeach; ?>
          </select><br>

          <p>This is set to 0, by default, but if your deploy is hitting FTP's API too rapidly, you can increase this to add a delay between each API request.</p>

        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ftp_test"><?php echo __('Test FTP Credentials', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <button id="ftp-test-button" type="button" class="btn-primary button">Test FTP Settings</button>
          <div class="spinner is-active" style="float:none;width:auto;height:auto;padding:10px 0 10px 50px;;"> </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>
