<div class="github_settings_block" style="display:none;">
  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-github"><?php echo __('Base URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-github', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ghToken"><?php echo __('Personl Access Token', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ghToken', 'GitHub Personal Access Token', '<a href="https://github.com/settings/tokens/new" target="_blank">How do I get this?</a>', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ghRepo"><?php echo __('Account & Repository Name', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ghRepo', 'Account / Repository Name', 'ie, leonstafford/wordpress-static-html-plugin'); ?><br>

          <p><i>Repository cannot be empty, just create any file via the GitHub UI if needed</i></p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ghBranch"><?php echo __('Branch', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ghBranch', 'Branch', 'usually \'master\' or \'gh-pages\''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="ghPath"><?php echo __('Path within repo', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'ghPath', 'Path within repository', 'Usually the repository root (leave this blank) or the \'doc\' folder'); ?>
        </td>
      </tr>
    </tbody>
  </table>
</div>
