<div class="netlify_settings_block" style="display:none;">

		<?php if ( ! extension_loaded('zip') ) : ?>

   <div class="notice notice-error inline wp2static-notice">
     <h2 class="title">WARNING: ZIP extension missing</h2>

     <p>This can be a common issue but easy to fix. It means that the installation of the PHP programming language on your web host does not currently have support for reading and generating compressed ZIP files. This is needed for the plugin to be able to generate a .zip archive of your static website. Here's some hosting company and platform specific guides on how to fix:</p>

     <ul>
         <li><a target="_blank" href="https://godaddy.com/help/enable-custom-php-modules-12036">GoDaddy</a></li>
         <li><a target="_blank" href="https://stackoverflow.com/questions/23564138/how-to-enable-zip-dll-in-xampp">XAMPP</a></li>
         <li><a target="_blank" href="https://stackoverflow.com/questions/38104348/install-php-zip-on-php-5-6-on-ubuntu">Ubuntu</a></li>
         <li><a target="_blank" href="https://www.digitalocean.com/community/questions/php-7-0-ziparchive-library-is-missing-or-disabled">DigitalOcean</a></li>
         <li><a target="_blank" href="http://lmgtfy.com/?q=how+to+get+zip+extension+php">Ask Dr. Google</a></li>
     </ul>

     <p>After installing/enabling the ZIP extension for PHP, you will likely also need to restart your webserver (Apache or nginx) for it to be usable within WordPress and this plugin.</p>

  </div>

  <?php endif;?>

  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-netlify"><?php echo __('Destination URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseUrl-netlify', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="netlifyPersonalAccessToken"><?php echo __('Personal Access Token', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'netlifyPersonalAccessToken', 'Netlify Personal Access Token', '<a href="https://app.netlify.com/account/applications/personal" target="_blank">How do I get this?</a>', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="netlifySiteID"><?php echo __('Site ID', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'netlifySiteID', 'Netlify Site ID', 'supports: mystaticsite, mystaticsite.netlify.com, mydomain.com, 3970e0fe-8564-4903-9a55-c5f8de49fb8b'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="netlifyRedirects"><?php echo __('Redirects File', 'static-html-output-plugin');?></label>
          <p><a href="https://www.netlify.com/docs/redirects/" target="_blank">more info</a></p>
        </th>
        <td>
          <textarea class="widefat" name="netlifyRedirects" id="netlifyRedirects" rows="5" cols="10"><?php echo $this->options->netlifyRedirects ? $this->options->netlifyRedirects : ''  ?></textarea>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="netlifyHeaders"><?php echo __('Headers File', 'static-html-output-plugin');?></label>
          <p><a href="https://www.netlify.com/docs/headers-and-basic-auth/" target="_blank">more info</a></p>
        </th>
        <td>
          <textarea class="widefat" name="netlifyHeaders" id="netlifyHeaders" rows="5" cols="10"><?php echo $this->options->netlifyHeaders ? $this->options->netlifyHeaders : ''  ?></textarea>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="netlify_test"><?php echo __('Test Netlify Settings', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <button id="netlify-test-button" type="button" class="btn-primary button">Test Netlify Settings</button>
        <span id="netlify_test_results"></span>
        </td>
      </tr>
    </tbody>
  </table>
</div>
