<div class="s3_settings_block" style="display:none;">

  <?php if (  wpsho_fr()->is_not_paying() ) : ?>

  <div class="notice notice-error inline">
    <h2 class="title">Premium deployment option</h2>

    <p>Get all the deployment options and advanced features with a 
      <a href="<?php echo wpsho_fr()->get_upgrade_url(); ?>">premium subscription</a>.</p>

    <p>Exporting to this method will not work without upgrading, but you can stil deploy to S3 using the ZIP option and manually uploading to S3.</p>

  </div>

  <br>

  <?php endif; ?>

  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="baseUrl-s3"><?php echo __('Base URL', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php echo displayTextfield($this, 'baseUrl-s3', 'http://mystaticsite.com', '', ''); ?><br>

          <p><i>Set this to the URL your visitors will use to access your site. For an S3 hosted website, you have a few options which will influence what you put in this field.</i></p>

          <ul>
            <li><b>Direct bucket hosting</b> If you want to serve your site directly from S3, you'll want the Endpoint as shown in your AWS console, when you go to your bucket > properties > Static website hosting, ie for a bucket named 'statictestfrankfurt', hosted in the eu-central-1 region, it will be: http://statictestfrankfurt.s3-website.eu-central-1.amazonaws.com.  </li>

            <li><b>Bucket with a custom domain</b> If you've setup a custom domain to use with your S3 bucket hosted, use that domain. In this case, your bucket name should already be the same as the domain, ie statictest.mydomain.org, with an A record alias entry in Route53 or your DNS provider to s3-website-ap-southeast-1.amazonaws.com. So, we would use http://statictest.mydomain.org/ as the Base Url in this case. 
            </li>

            <li><b>S3 hosted website cached with CloudFront</b> If you've setup CloudFront to speed up your S3 hosted static site, then entering your CloudFront Distribution ID here will send a cache invalidation request after all the files have been deployed to S3. It will use the same AWS credentials as S3, so ensure that IAM user in AWS has the correct permissions for both S3 and CloudFront. You could set the BaseURL to the CloudFront address, ie http://d3fvx8eaa0pipc.cloudfront.net/, but more than likely, you have another domain you want to use for the website, so set the Base Url to that, ie https://mywebsite.com.</li>
          </ul>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="s3Key"><?php echo __('Access Key ID', 'static-html-output-plugin');?></label>
        </th>
        <td>
         <?php echo displayTextfield($this, 's3Key', 'Access Key ID', 'ie, AKIAIOSFODNN7EXAMPLE'); ?><br>

          <p><i>Your S3 user will need permissions to put objects into the bucket. Check that the user whose Key you are using has the correct permissions for S3. You may attach the 'AmazonS3FullAccess' to the user or give more fine grained permissions control via <a href="https://aws.amazon.com/iam/" target="_blank">AWS's IAM</a>.</i></p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="s3Key"><?php echo __('Secret Access Key', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php echo displayTextfield($this, 's3Secret', 'Secret Access Key', 'ie, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="s3Region"><?php echo __('Region', 'static-html-output-plugin');?></label>
        </th>
        <td>
        <?php 

        // TODO: shift to S3 model/helper
        $s3_regions = array(
          "us-east-1" => "US East (N. Virginia)",
          "us-east-2" => "US East (Ohio)",
          "us-west-1" => "US West (N. California)",
          "us-west-2" => "US West (Oregon)",
          "ca-central-1" => "Canada (Central)",
          "ap-south-1" => "Asia Pacific (Mumbai)",
          "ap-northeast-2" => "Asia Pacific (Seoul)",
          "ap-southeast-1" => "Asia Pacific (Singapore)",
          "ap-southeast-2" => "Asia Pacific (Sydney)",
          "ap-northeast-1" => "Asia Pacific (Tokyo)",
          "ap-northeast-3" => "Asia Pacific (Osaka-Local)",
          "eu-central-1" => "EU (Frankfurt)",
          "eu-west-1" => "EU (Ireland)",
          "eu-west-2" => "EU (London)",
          "eu-west-3" => "EU (Paris)",
          "sa-east-1" => "South America (São Paulo)",
          "cn-north-1" => "China (Beijing)",
          "cn-northwest-1" => "China (Ningxia)",
        );
        ?>

          <?php echo displaySelectMenu($this, $s3_regions, 's3Region', 'Region', 'ie, my-static-site'); ?><br>

          <span class="description">choose the AWS region your bucket was created in</span>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="s3Bucket"><?php echo __('Bucket', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php echo displayTextfield($this, 's3Bucket', 'S3 Bucket', 'ie, my-static-site'); ?><br>

          <p><i>Your bucket name as it appears in your <a href="https://s3.console.aws.amazon.com/s3/home" target="_blank">AWS Console for S3</a>.</i></p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="s3RemotePath"><?php echo __('Subdirectory', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php echo displayTextfield($this, 's3RemotePath', 'Subfolder in your bucket', 'ie, static-website'); ?><br>

          <p><i>In case you want to put your site in a sub directory of a bucket, this will deploy all the static website files into the folder name you specify here.</i></p> 
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="cfDistributionId"><?php echo __('CloudFront Cache Invalidation', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php echo displayTextfield($this, 'cfDistributionId', 'CloudFront Distribution ID', 'ie, ABC123DEFX'); ?><br>

          <p><i>If using CloudFront in your S3 static website setup, enter the CloudFront Distribution ID here and it will create an invalidation request for all files at the end of the deployment process. The invalidation usually happens within a few minutes. You can check any pending invalidations in your <a href="https://console.aws.amazon.com/cloudfront/home" target="_blank">AWS Console's CloudFront page</a>. You AWS user will need to have the CloudFrontFullAccess permissions or a more controlled policy, that includes the ability to send CloudFront invalidation requests.</i></p>
        </td>
      </tr>
    </tbody>
  </table>
</div>
