<?php
/**
 * @package WP Static HTML Output
 *
 * Copyright (c) 2011 Leon Stafford
 */

$fail = array();
$pass = array();

if (!$this->supportsZipArchives):
	$fail[] = 'You are missing the <strong>zip</strong> extension';
else:
	$pass[] = 'You have the <strong>zip</strong> extension';
endif;

if (!$this->uploadsFolderWritable):
	$fail[] = 'Your uploads folder ('. $this->uploadsFolder['path']  .') is not writable.';
else:
	$pass[] = 'Your uploads folder ('. $this->uploadsFolder['path']  .') is writable';
endif;

if (!$this->permalinksStructureDefined):
	$fail[] = 'Your permalinks structure is undefined. Please set your permalinks structure here: <a href="'.admin_url( 'options-permalink.php' ).'">Permalink Settings</a>';
else:
	$pass[] = 'Your permalinks structure is ok.';
endif;
?>

<div class="wrap wpsho-report">
	
	<h2>Pre-flight check - is your system able to run the WP Static HTML Output plugin?</h2>
	
	<p><strong>Oops - we need to fix some things before the plugin will run smoothly for you.</strong></p>
	
	<p>
		The following requirements failed, please contact the plugin developer, <a href="https://leonstafford.github.io">Leon Stafford</a>, for some support with your issue.
		<ul>
			<li><?php echo implode('</li><li>', $fail) ?></li>
		</ul>
	</p>
	
	<?php if (count($pass)): ?>
	<p>
		The following requirements were successfully met:
		<ul>
			<li><?php echo implode('</li><li>', $pass) ?></li>
		</ul>
	</p>
	<?php endif ?>
	
</div>
