<?php
/**
 * @package WP Static HTML Output
 *
 * Copyright (c) 2011 Leon Stafford
 */

$fail = array();
$pass = array();

if (!$this->supports_cURL):
	$fail[] = 'You are missing the <strong>cURL</strong> extension for PHP';
else:
	$pass[] = 'You have the <strong>cURL</strong> extension';
endif;

if (!$this->uploadsFolderWritable):
	$fail[] = 'Your uploads folder ('. $this->uploadsPath  .') is not writable.';
else:
	$pass[] = 'Your uploads folder ('. $this->uploadsPath  .') is writable';
endif;

if (!$this->permalinksStructureDefined):
	$fail[] = 'Your permalinks structure is undefined. Please set your permalinks structure here: <a href="'.admin_url( 'options-permalink.php' ).'">Permalink Settings</a>';
else:
	$pass[] = 'Your permalinks structure is ok.';
endif;
?>

<div class="wrap wpsho-report">
	
	<h2>Pre-flight check - is your system able to run the WP Static HTML Output plugin?</h2>
	
	<p><strong>Oops - we need to fix some things before the plugin will run smoothly for you.</strong></p>
	
	<p>
		The following requirements failed, please contact the plugin developer, <a href="https://leonstafford.github.io">Leon Stafford</a>, for some support with your issue or see tips below.
		<ul>
			<li><?php echo implode('</li><li>', $fail) ?></li>
		</ul>

		<h3>Missing the ZIP extension?</h3>


		<h3>Missing the cURL extension?</h3>

        <p> This is a library that allows the plugin to better export your static site out to services like GitHub, S3, Dropbox, BunnyCDN, etc. It's usually an easy fix to get this working. You can try Googling "How to enable cURL extension for PHP", along with the name of the environment you are using to run your WordPress site. This may be something like DigitalOcean, GoDaddy or LAMP, MAMP, WAMP for your webserver on your local computer. If you're still having trouble, the developer of this plugin is easger to help you get up and running. Please email him at <a href="mailto:leonstafford@protonmail.com">leonstafford@protonmail.com</a> and he'll sort you out.</p>

	</p>

		<h3>Need to set your permalinks?</h3>

        <p>Due to the nature of how static sites work, you'll need to have some kind of permalinks structure defined in your <a href="'.admin_url( 'options-permalink.php' ).'">Permalink Settings</a> within WordPress. To learn more on how to do this, please see WordPress's official guide to the <a href="https://codex.wordpress.org/Settings_Permalinks_Screen">Settings Permalinks Screen</a>.</p>
	
	<?php if (count($pass)): ?>
		<h3>It's not all bad - here's what you've got working already:</h3>
	<p>
		The following requirements were successfully met:
		<ul>
			<li><?php echo implode('</li><li>', $pass) ?></li>
		</ul>
	</p

	<p>You're so close! Don't give up now - this plugin may just solve some big problems for you. Please email the developer personally at <a href="mailto:leonstafford@protonmail.com">leonstafford@protonmail.com</a>, he wants this software to make a differnce to everyone and will go out his way to troubleshoot any issues with you!</p>
	<?php endif ?>
	
</div>
