<div class="export_your_site">


<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <label for="selected_deployment_option"><?php echo __('Where will you host the optimized version of your site?', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <select class="selected_deployment_method" name="selected_deployment_option">
          <?php generateDeploymentMethodOptions(); ?>
        </select>
      </td>
    </tr>
  </tbody>
</table>



<!-- legacy multi-export functionality relied on the baseUrl field being first in the settings block -->
<input style="display:none;" type="text" id="baseUrl" name="baseUrl" value="<?php echo esc_attr($this->baseUrl) ?>" size="50" placeholder="http://mystaticsite.com" />


<?php

  // load up each deployment settings block
  $deployment_option_templates = array(
    __DIR__ . '/folder_settings_block.phtml',
    __DIR__ . '/zip_settings_block.phtml',
    __DIR__ . '/ftp_settings_block.phtml',
    __DIR__ . '/s3_settings_block.phtml',
    __DIR__ . '/s3_settings_block.phtml',
    __DIR__ . '/bunnycdn_settings_block.phtml',
    __DIR__ . '/netlify_settings_block.phtml',
    __DIR__ . '/github_settings_block.phtml',
    __DIR__ . '/gitlab_settings_block.phtml',
    __DIR__ . '/bitbucket_settings_block.phtml',
  );

  $deployment_option_templates = apply_filters(
      'wp2static_load_deploy_option_template',
      $deployment_option_templates
  );

  foreach( $deployment_option_templates as $deployment_option_template ) {
    require_once( $deployment_option_template );
  }

?>

</div> <!-- end export_your_site -->

