<div class="help_troubleshooting">

<main class="wp2static-content">
  <p>Congratulations on choosing to <b>Go Static</b>!</p>
</main>

<section class="wp2static-content"> 
  <p>We think it's the best way to deal with 90% of WordPress sites, but the concept does take a little while to get used to.</p>

  <p>The tabs above are presented in a logical order for you to check/adjust settings.</p>

  <p>We understand this can be daunting at first. Please use the links below to review documentation, especially the "Getting Started" section in the <a href="https://wp2static.com/documentation" target="_blank">documentation</a>.</p>
</section>

<section class="wp2static-content">
  
</section>

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-book-alt"></span>
        <label><?php echo __('Documentation', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://wp2static.com/documentation" target="_blank">
          Official documentation and tutorials at wp2static.com
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-video-alt3"></span>
        <label><?php echo __('Videos', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://www.youtube.com/watch?v=HPc4JjBvkrU" target="_blank">
            WordPress as a Static Site Generator
        </a>
        <p>A good introduction to what a static site is and how it can benefit your WordPress site.</p>
      </td>

    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-sos"></span>
        <label><?php echo __('Create Support Request', 'static-html-output-plugin');?></label>
      </th>
      <td>

        <p>Get help from the WP2Static team - we'll open a ticket for you and follow-up soon!</p>

        <br>

          <label for="supportRequestEmail">
            <?php echo __('Your email', 'static-html-output-plugin');?>
          </label>

        <br>
        <br>

<?php

// default support request to user email
global $current_user;
get_currentuserinfo();

?>

        <input type="text" id="supportRequestEmail" name="supportRequestEmail" value="<?php echo $current_user->user_email ?>" size="50" />

        <br>
        <br>
          <label for="supportRequestContent">
            <?php echo __('Your issue', 'static-html-output-plugin');?>
          </label>
        <br>
        <br>

<textarea class="widefat" name="supportRequestContent" id="supportRequestContent" rows="5" cols="10">
Example:

Help! I'm having trouble with exporting my site - it's missing some images and fonts.
I'm hosting with Acme Company. I'm new to WordPress.
Attached is my Debug Log to give you more info.

        </textarea>
        <br>
        <br>

          <label for="supportRequestIncludeLog"><?php echo __('', 'static-html-output-plugin');?></label>
          <?php $tpl->displayCheckbox($this, 'supportRequestIncludeLog', 'Include Debug Log (helps us diagnose quicker)'); ?>

        <br>

        <button id="send_support_request">Create new support request</button>

        <br>
        <br>

        <p>Check the status of your ticket or create one via the web: <a href="https://wp2static.zammad.com" target="_blank">https://wp2static.zammad.com</a>.</p>

      </td>

    </tr>
  </tbody>
</table>




</div> <!-- end advanced settings -->

