<div class="processing_settings" style="display:none;">

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <label for="useRelativeURLs"><?php echo __('Use relative URLs', 'static-html-output-plugin');?></label>
      </th>
      <td>

        <?php $tpl->displayCheckbox($this, 'useRelativeURLs', 'Use relative URLs'); ?>

        <p> URLs in the exported site will be rewritten as <a href="https://www.w3schools.com/tags/tag_base.asp" target="_blank">relative URLs</a>. ie, <code>http://mydomain.com/some_dir/some_file.jpg</code> will become <code>some_dir/some_file.jpg</code></p>
      </td>
    </tr>
      <tr>
        <th scope="row">
          <label for="baseHREF"><?php echo __('Base HREF', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'baseHREF', 'Base HREF', '', ''); ?>

          <p>Setting this will tell the browser to resolve all URLs using this as a base. ie, with a Base HREF of <code>/</code> and the relative URL setting enabled above, a relative link of <code>some_dir/some_file.jpg</code> will resolve to <code>/some_dir/some_file.jpg</code></p>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label><?php echo __('Custom rewrites in exported source code', 'static-html-output-plugin');?></label>
        </th>
        <td>
        <p>In order to hide any trace that your site uses WordPress, you can choose to rewrite common URL structures, such as wp-content/themes, etc.</p>
    
        <p>You can also rewrite external URLs or arbitray text. WP2Static rewrites exactly what you specify as search and replace strings.</p>

        <p>Replace, for example, default WordPress paths within the source code</p> <br>

        <p>use the full path, such as:</p>

        <pre>
            wp-content/themes/twentyseventeen/,contents/ui/mytheme/
            wp-includes/,inc/
        </pre>
    
        <p>The plugin does its best to sort rewrite rules in order needed, to process the longest items first.</p>

        <br>

          <textarea class="widefat" name="rewrite_rules" id="rewrite_rules" rows="5" cols="10"><?php echo $this->options->rewrite_rules ? $this->options->rewrite_rules : '';  ?></textarea>
        </td>
    </tr>
    <tr>
        <th scope="row">
          <label><?php echo __('Rename Exported Directories', 'static-html-output-plugin');?></label>
        </th>
        <td>
        <p>Required if rewriting any local URLs within the site.</p><br>

        <p>Set the source directory, then a comma and the target directory. </p

        <p>
In order to move wp-content/themes/twentyseventeen to contents/ui/mytheme, we'd need:
</p>

<pre>
wp-content,contents
contents/themes,contents/ui
contents/ui/twentyseventeen,contents/ui/mytheme
wp-includes/,inc/
</pre>



         <br>

          <textarea class="widefat" name="rename_rules" id="rename_rules" rows="5" cols="10"><?php echo $this->options->rename_rules ? $this->options->rename_rules : '';  ?></textarea>
        </td>
    </tr>
    <tr>
      <th scope="row">
        <label for="stripping"><?php echo __('Remove cruft', 'static-html-output-plugin');?></label>
      </th>
      <td>

        <?php $tpl->displayCheckbox($this, 'removeConditionalHeadComments', 'Remove conditional comments within HEAD', 'checked'); ?>

        <p>Mostly obsolete, previously used for detecting versions of Internet Explorer and serving different CSS or JS.</p><br>

        <?php $tpl->displayCheckbox($this, 'removeWPMeta', 'Remove WP Meta tags'); ?>

        <p>The <code>&lt;meta&gt; name="generator" content="WordPress 4.9.8" /&gt;</code> type tags.</p><br>

        <?php $tpl->displayCheckbox($this, 'removeWPLinks', 'Remove WP &lt;link&gt; tags'); ?>

        <p>ie, <code>&lt;link& rel="EditURI"...</code> type tags that usually aren't needed.</p><br>

        <?php $tpl->displayCheckbox($this, 'removeHTMLComments', 'Remove HTML comments'); ?>

        <p>ie, <code>&lt;!-- / Yoast SEO plugin. --&gt;</code> type comments that are ridiculously wasting bytes</p><br>

        <?php $tpl->displayCheckbox($this, 'removeCanonical', 'Remove Canonical tags from pages (best left unchecked)'); ?>

        <p>Search engines use the canonical tag to identify how to index a page.  i.e domain.com/page/ and domain.com/page/index.html are 2 different URLs that represent the same page. This could trigger a duplicate content penalty.  The canonical tag tells the search engine that they are same page and they should be indexed as domain.com/page/</p><br>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <label for="Modifications"><?php echo __('Modify HTML', 'static-html-output-plugin');?></label>
      </th>
      <td>

        <?php $tpl->displayCheckbox($this, 'createEmptyFavicon', 'Insert empty icon rel to prevent favicon requests', 'checked'); ?>

        <p>If you don't have a favicon for your site, block extra requests taking up speed</p><br>
      </td>
    </tr>
  </tbody>
</table>

</div><!-- end processing_setings -->
