<div class="advanced_settings" style="display:none;">

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <label for="diffBasedDeploys"><?php echo __('Diff-based deployment', 'static-html-output-plugin');?></label>
      </th>
      <td>

        <?php echo displayCheckbox($this, 'diffBasedDeploys', 'Only deploy changed files since last export'); ?>

        <p>
        As this works off of your last export, if you have changed the deployment method or settings since your last deployment, you may end up with missing files. In this case, uncheck this option, do one complete deployment with your new settings, then re-enable this to get faster deployments of changes only going forward.
        </p>

      </td>
    </tr>
    <tr>
      <th scope="row">
        <label for="outputDirectory"><?php echo __('Override Output Directory', 'static-html-output-plugin');?></label>
      </th>
      <td>
          <?php echo displayTextfield($this, 'outputDirectory', '', '', ''); ?>

          <p><i>Just leave this blank and it will write any export files to your WordPress uploads directory at: <?php echo $this->uploadsPath; ?> else, give the full path to the directory on your server</i></p>

      </td>
    </tr>
    <tr>
      <th scope="row">
        <label for="crawl_increment"><?php echo __('Crawl Increment', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <select name="crawl_increment" id="crawl_increment">
<?php 
  // TODO: shift this into helper function for select
  $increments = array(1, 5, 10, 25, 50, 100, 500, 1000, 999999);

  foreach($increments as $increment) :
     if ($increment == 999999): ?>
          <option value="999999"<?php echo $this->options->crawl_increment == $increment ? ' selected' : ''; ?>>Maximum</option>
<?php else: ?>
          <option value="<?php echo $increment; ?>"<?php echo $this->options->crawl_increment == $increment ? ' selected' : ''; ?>><?php echo $increment; ?></option>

<?php endif; 
       endforeach; ?>
        </select><br>

        <p>This is set to 1, by default, in order to allow exporting on low-resource environments, such as shared hosting servers. Each increment is the amount of files the server will try to process on each request that the browser sends it. Incrementing this will speed up your exports, by processing more are a time. If your export is failing, due to resource (memory, CPU) limits being reached, try setting this to a lower number.</p>

      </td>
    </tr>
    <tr>
      <th scope="row">
        <label for="wp_static_html_output_server_side_export_hook"><?php echo __('Scheduled deploys', 'static-html-output-plugin');?></label>
      </th>
      <td>
          <input type="text" style="width:340px;" value="wp_static_html_output_server_side_export_hook" disabled /><br>

          <p>Using the <a href="https://wordpress.org/plugins/wp-crontrol/" target="_blank">WP Crontrol</a> plugin, you can add the following hook to a schedule to trigger an export. This will run your export using the settings you've saved via this screen. Using this method, you can schedule your exports to happen daily or if you're after an on-post publish kind of behaviour, you could set this to every few minutes.</p><br>

      <?php if ( ! wpsho_fr()->is_plan('professional_edition') ) : ?>
           <a href="<?php echo wpsho_fr()->get_upgrade_url(); ?>">
                  Upgrade to the Professional Edition for programmatic access
                  </a>
      <?php endif;?>

      </td>
    </tr>
    <tr>
      <th scope="row">
          <label><?php echo __('Redirect this domain to your static site?', 'static-html-output-plugin');?></label>
      </th>
      <td>
          <p>If you're happy with how your site is looking after exporting to a subdirectory, you can choose to start serving this content to your visitors, instead of your current WordPress site. To do this, you will need to adjust your <code>.htaccess</code> file. This <a href="" target="_blank">community guide</a> may be able to help you.
      </td>
    </tr>
  </tbody>
</table>




</div> <!-- end advanced settings -->

