<div class="add_ons" style="display:none;">

<section class="wp2static-content">
  <p>Whilst you can get a fully functioning static site using the free version of WP2Static, our suite of <a href="https://wp2static.com" target="_blank">Add-ons</a> give you a range of powerful enhancements. Browse our premium and free Add-ons for faster and more powerful static site exports.</p>
</section>

<section class="wp2static-content-addon">

<?php

$add_ons = array(
    'wp2static-addon-azure/wp2static-addon-azure.php' => 'Azure',
    'wp2static-addon-bitbucket/wp2static-addon-bitbucket.php' => 'Bitbucket',
    'wp2static-addon-bunnycdn/wp2static-addon-bunnycdn.php' => 'BunnyCDN',
    'wp2static-addon-ftp/wp2static-addon-ftp.php' => 'FTP',
    'wp2static-addon-github/wp2static-addon-github.php' => 'GitHub',
    'wp2static-addon-gitlab/wp2static-addon-gitlab.php' => 'GitLab',
    'wp2static-addon-netlify/wp2static-addon-netlify.php' => 'Netlify',
    'wp2static-addon-s3/wp2static-addon-s3.php' => 'S3',
    'wp2static-addon-now/wp2static-addon-now.php' => 'now'
);

?>

<?php foreach( $add_ons as $add_on_code => $add_on_name ): ?>

  <div class="content addon wp2static-column">
    <div class="main">
      <img src="<?php echo strtolower( plugins_url( "/../wpassets/$add_on_name.svg", __FILE__ ) ) ;?>" alt="" class="hero">
      <h2><?php echo $add_on_name; ?> Add-on</h2>
      <p>Deploy your site statically with <?php echo $add_on_name; ?> Add-on and feels the speed!</p>
    </div>
    <div class="bottom">
      <div class="left">
        <?php if( is_plugin_active( $add_on_code ) ) : ?>
        <a href="" class="wp2static-btn btn-call-to-action">
          Active
        </a>
        <?php else: ?>
        <a href="" class="wp2static-btn">
          Get Add-on
        </a>
        <?php endif; ?>
      </div>
      <div class="right"><a href=""><img src="<?php echo strtolower( plugins_url( "/../wpassets/github.svg", __FILE__ ) ) ;?>" alt="" style="max-width:32px"></a></div>
    </div>
  </div>

<?php endforeach; ?>

</section>

</div> <!-- end add-ons tab -->