<div class="give_love" style="display:none;">

<p>
This is first and foremost free, <a href="" target="https://github.com/leonstafford/wordpress-static-html-plugin/">open source</a> software, but aiming to cover development, support and promotional costs via the <a href="https://wp2static.com" target="_blank">PowerPack</a> premium add-on.
</p>

<h2>Other ways to support this plugin</h2>

<table class="form-table">
  <tbody>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-wordpress-alt"></span>
        <label><?php echo __('Leave a review', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://wordpress.org/support/plugin/static-html-output-plugin/reviews/" target="_blank">
          Official WordPress.org reviews for WP2Static
        </a>

        <p>Reviews play a large part in helping people decide to try a plugin. Try to include how the plugin helped you solve a particular problem.</p>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-book-alt"></span>
        <label><?php echo __('Documentation', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://github.com/leonstafford/wp-static-site-generator-documentation" target="_blank">
            Help write / translate our documentation
        </a>

        <p>A never-ending, continual improvement process that benefits from any input. Instructions on the linked page. If it's too technical, make contact and we can find another way to get your contributions.</p>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-twitter"></span>
        <label><?php echo __('Spread the word', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://twitter.com/wp2static" target="_blank">
          Tweet about @wp2static
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-format-chat"></span>
        <label><?php echo __('Help others', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://wp2static.com/community/" target="_blank">
            Help other users in our forums, StackExchange, Slack, Twitter, GitHub Issues or official WordPress.org plugin support page.
        </a>

        <p>We want to help more people realize the benefits of going static and easing their transition. Be there to help answer questions and support each other.</p>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-video-alt3"></span>
        <label><?php echo __('Video tutorials', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://www.youtube.com/watch?v=JmU6lrB8bRs" target="_blank">
          Create screencasts/tutorials
        </a>

        <p>Many people prefer to learn visually, with video tutorials a really effective way to convey the whole WordPress to static site solution. If you make a how-to video or other WordPress to static or general static website video, we'll happily promote it for you.</p> 
      </td>
    </tr>
  </tbody>
</table>




</div> <!-- end advanced settings -->

