<div class="help_troubleshooting">

<table class="form-table">
  <tbody>
    <tr>
      <td colspan="2">
        <p>Congratulations on choosing to <b>Go Static</b>!</p>

        <br>

        <p>We think it's the best way to deal with 90% of WordPress sites, but the concept does take a little while to get used to.</p>

        <br>

        <p>The tabs above are presented in a logical order for you to check/adjust settings.</p>

        <br>

        <p>We understand this can be daunting at first. Please use the links below to review documentation, especially the "Getting Started" section in the <a href="https://wp2static.com/documentation" target="_blank">documentation</a>.</p>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-book-alt"></span>
        <label><?php echo __('Documentation', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://wp2static.com/documentation" target="_blank">
          Official documentation and tutorials at wp2static.com
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-format-chat"></span>
        <label><?php echo __('Community', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://join.slack.com/t/wp2static/shared_invite/enQtNDQ4MDM4MjkwNjEwLTVmN2I2MmU4ODI2MWRkNzM4ZGU3YWU4ZGVhMzgwZTc1MDE2OGNmYTFhOGMwM2U0ZTVlYTljYmM2Yjk2ODJlOTk" target="_blank">
          Join our 200+ users & developers in our Slack community
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-twitter"></span>
        <label><?php echo __('Follow on Twitter', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://twitter.com/WP2Static" target="_blank">
          Follow us on Twitter for latest news and offers
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <span class="dashicons dashicons-star-filled"></span>
        <label><?php echo __('Star on GitHub', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <a href="https://github.com/WP2Static/wp2static" target="_blank">
          Follow the main or development branches to preview the latest code
        </a>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <label><?php echo __('Videos', 'static-html-output-plugin');?></label>
      </th>
      <td>
        
        <a href="https://www.youtube.com/watch?v=HPc4JjBvkrU" target="_blank">
            <span class="dashicons dashicons-video-alt3"></span> WordPress as a Static Site Generator

        </a>

        <p>A good introduction to what a static site is and how it can benefit your WordPress site.</p>
      </td>

    </tr>
  </tbody>
</table>




</div> <!-- end advanced settings -->

