<div class="crawl_settings" style="display:none;">

  <table class="form-table">
    <tbody>
      <tr>
        <th scope="row">
          <label for="crawl_increment"><?php echo __('Crawl Increment', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <select name="crawl_increment" id="crawl_increment">
  <?php 
    // TODO: shift this into helper function for select
    $increments = array(1, 5, 10, 25, 50, 100, 500, 1000, 999999);
  
    foreach($increments as $increment) :
       if ($increment == 999999): ?>
            <option value="999999"<?php echo $this->options->crawl_increment == $increment ? ' selected' : ''; ?>>Maximum</option>
  <?php else: ?>
            <option value="<?php echo $increment; ?>"<?php echo $this->options->crawl_increment == $increment ? ' selected' : ''; ?>><?php echo $increment; ?></option>
  
  <?php endif; 
         endforeach; ?>
          </select><br>
  
          <p>This is set to 1, by default, in order to allow exporting on low-resource environments, such as shared hosting servers. Each increment is the amount of files the server will try to process on each request that the browser sends it. Incrementing this will speed up your exports, by processing more are a time. If your export is failing, due to resource (memory, CPU) limits being reached, try setting this to a lower number.</p>
  
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="useBasicAuth"><?php echo __('Use basic authentication', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayCheckbox($this, 'useBasicAuth', 'My WP site requires Basic Auth to access'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="basicAuthUser"><?php echo __('Basic auth user', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'basicAuthUser', 'Basic Auth user', '', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="basicAuthPassword"><?php echo __('Basic auth password', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'basicAuthPassword', 'Basic Auth password', '', 'password'); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="crawlPort"><?php echo __('Custom crawling port', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayTextfield($this, 'crawlPort', 'Custom crawling port', ''); ?>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label><?php echo __('Exclude certain URLs', 'static-html-output-plugin');?></label>
        </th>
        <td>
        <p>Where the plugin has detected too many files and you want to exclude certain URLs from being crawled, please specify these URLs here.</p> <br>

        <i><p>You can enter this as a partial string or full path</p> <br>

        <?php echo $this->wp_site_url; ?>/wp-content/themes/twentyseventeen/banana.jpg<br>
        /my_pricelist.pdf<br>
        .js<br>
        </i>
        <br>

          <textarea class="widefat" name="excludeURLs" id="excludeURLs" rows="5" cols="10"><?php echo $this->options->excludeURLs ? $this->options->excludeURLs : ''  ?></textarea>
        </td>
      </tr>
      <tr>
        <th scope="row">
          <label for="parse_css"><?php echo __('Parse CSS files', 'static-html-output-plugin');?></label>
        </th>
        <td>
          <?php $tpl->displayCheckbox($this, 'parse_css', 'Parse CSS files'); ?>

        <p>
            This will result in better exports, but will consume more memory on the server. Try disabling this if you're unable to complete your export and suspect it's running out of memory.
        </p>
        </td>
      </tr>
    <tr>
      <th scope="row">
        <label for="crawl_delay"><?php echo __('Crawl Delay', 'static-html-output-plugin');?></label>
      </th>
      <td>
        <select name="crawl_delay" id="crawl_delay">
<?php 
  // TODO: shift this into helper function for select
  $delays = array(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 3, 4, 10);

  foreach($delays as $delay) : ?>
          <option value="<?php echo $delay; ?>"<?php echo $this->options->crawl_delay == $delay ? ' selected' : ''; ?>><?php echo $delay; ?></option>

       <?php endforeach; ?>
        </select><br>

        <p>This is set to 0, by default, for better performance, but if exports are failing and no error appears with Debug Log enabled or you see "Too many files open" or such errors in the server logs, try increasing this value until you get a successful export.</p>

      </td>
    </tr>
    </tbody>
  </table>
</div><!-- end crawl_setings -->
