<div class="export_logs" style="display:none;">

<br>

<p>Log files will be generated during export if the <b>Debug Mode</b> has been enabled (from within the Advanced tab).</p>

<button id="reload_log_button" class="button-secondary">(Re)load log</button>

<a href="<?php echo $this->wp_site->uploads_url; ?>/WP-STATIC-EXPORT-LOG.txt" class="button-secondary" target="_blank">Open log in new tab</a>


<div id="log_load_progress" class="pulsate-css" style="float:none;display:none;"></div>

<br>
<br>

<textarea id="export_log_textarea" style="width:100%;min-height:300px;" disabled>
Load log to show contents here
</textarea>


</div> <!-- end Debug Logs -->

